import bpy
import math as m
from math import *
import mathutils as mu
from mathutils import *
import numpy as np

def angvel_to_quat(omega_x, omega_y, omega_z, dt): # This was generated by ChatGPT. My understand of quaternions is not strong.
    theta = m.sqrt(omega_x**2 + omega_y**2 + omega_z**2) * dt
    if theta > 0:
        axis = np.array([omega_x, omega_y, omega_z]) / m.sqrt(omega_x**2 + omega_y**2 + omega_z**2)
        half_theta = theta / 2.0
        q_delta = mu.Quaternion((m.cos(half_theta), *(m.sin(half_theta) * axis)))
    else:
        q_delta = mu.Quaternion((1.0, 0.0, 0.0, 0.0))
    return q_delta

def get_angvel_values(input):
    x = input['angVelPitch'].value
    y = input['angVelRoll'].value
    z = input['angVelYaw'].value
    return radians(x), radians(y), radians(z)